version: "3"
services:
  api:
    build: .
    environment:
      - DB_PASS=123456
      - ADMIN_USERNAME=faili
      - ADMIN_PASSWORD=hesham@ut.ac.ir!
      - SECRET_KEY=as#4frRt!sfhjkl)
    ports:
      - "9000:80"
    links:
      - db
    volumes:
      - /home/mostafa/HSD:/code
    depends_on:
      db:
        condition: service_started
    restart: on-failure
    
  db:
    image: "mysql:latest"
    volumes:
      - /home/mostafa/HSD/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456